#!/usr/bin/env bash

send() {
  echo "${2}"
  stty 115200 -parenb cs8 -cstopb &&
  echo 'load' > /dev/ttyUSB$1 &&
  sleep 1 &&
  arm-none-eabi-objcopy -S -O srec "./target/thumbv7em-none-eabihf/release/$2" app.s19 &&
  cat app.s19 > /dev/ttyUSB$1 &&
  sleep 1 &&
  echo 'go' > /dev/ttyUSB$1
}

send $1 $2

